spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

auth-service:
  url: http://localhost:8081

websocket-service:
  url: http://localhost:8082

server:
  port: 8080

# JWT settings for development (DO NOT use this secret in production!)
jwt:
  secret: N7z1qvJSe3Et1fvPIe5x/kX3fvhOceODWkSpLsDJImo=
  expiration: 86400000 # 1 day in milliseconds

