spring:
  application:
    name: market-service

finnhub:
  url: https://finnhub.io/api/v1
  symbols:
    - AAPL
    - TSLA
    - MSFT
    - GOOGL
  apiKey: ${FINNHUB_API_KEY}

alphavantage:
  url: https://www.alphavantage.co
  symbols:
    - AAPL
    - MSFT
    - GOOGL
    - TSLA
  apiKey: ${ALPHAVANTAGE_API_KEY}

twelvedata:
  url: https://api.twelvedata.com
  symbols:
    - AAPL
    - MSFT
    - GOOGL
    - TSLA
  apiKey: ${TWELVEDATA_API_KEY}

kafka:
  bootstrap:
    servers: kafka:9092
  topic:
    quotes: market-quotes

server:
  port: 8085
