spring:
  application:
    name: news-service

newsapi:
  url: https://newsapi.org/v2/top-headlines
  category: business
  country: us
  apiKey: ${NEWSAPI_KEY}

kafka:
  bootstrap:
    servers: localhost:9092
  topic:
    news: news-updates

server:
  port: 8084